[2025-08-28T06:00:00.657+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T06:00:00.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T05:00:00+00:00 [queued]>
[2025-08-28T06:00:00.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T05:00:00+00:00 [queued]>
[2025-08-28T06:00:00.683+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T06:00:00.690+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_new_file> on 2025-08-28 05:00:00+00:00
[2025-08-28T06:00:00.696+0000] {standard_task_runner.py:63} INFO - Started process 398 to run task
[2025-08-28T06:00:00.698+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres', 'wait_for_new_file', 'scheduled__2025-08-28T05:00:00+00:00', '--job-id', '662', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres.py', '--cfg-path', '/tmp/tmpkf3g0h14']
[2025-08-28T06:00:00.700+0000] {standard_task_runner.py:91} INFO - Job 662: Subtask wait_for_new_file
[2025-08-28T06:00:00.711+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T06:00:00.734+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T05:00:00+00:00 [running]> on host 7a38bda25d96
[2025-08-28T06:00:00.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T05:00:00+00:00'
[2025-08-28T06:00:00.914+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T06:00:00.931+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7f5bc71280d0>
[2025-08-28T06:00:01.082+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-08-28T06:00:01.082+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T06:00:01.089+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_to_postgres, task_id=wait_for_new_file, run_id=scheduled__2025-08-28T05:00:00+00:00, execution_date=20250828T050000, start_date=20250828T060000, end_date=20250828T060001
[2025-08-28T06:00:01.110+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-28T06:00:01.130+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-28T06:00:01.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
